<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13190" started-at="2021-08-23T11:03:32 IST" finished-at="2021-08-23T11:03:45 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="13190" started-at="2021-08-23T11:03:32 IST" finished-at="2021-08-23T11:03:45 IST">
      <class name="Tests.CompareTemperature">
        <test-method status="PASS" signature="setTestConfig(java.lang.String)[pri:0, instance:Tests.CompareTemperature@71a794e5]" name="setTestConfig" is-config="true" duration-ms="8313" started-at="2021-08-23T11:03:32 IST" finished-at="2021-08-23T11:03:40 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTestConfig -->
        <test-method status="PASS" signature="TC1_GetWeatherFromAccu()[pri:0, instance:Tests.CompareTemperature@71a794e5]" name="TC1_GetWeatherFromAccu" duration-ms="3714" started-at="2021-08-23T11:03:40 IST" finished-at="2021-08-23T11:03:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1_GetWeatherFromAccu -->
        <test-method status="PASS" signature="TC2_GetWeatherFromOpenWeather()[pri:1, instance:Tests.CompareTemperature@71a794e5]" name="TC2_GetWeatherFromOpenWeather" duration-ms="452" started-at="2021-08-23T11:03:44 IST" finished-at="2021-08-23T11:03:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2_GetWeatherFromOpenWeather -->
        <test-method status="FAIL" signature="TC3_CompareTwoWeathers()[pri:2, instance:Tests.CompareTemperature@71a794e5]" name="TC3_CompareTwoWeathers" duration-ms="1" started-at="2021-08-23T11:03:44 IST" finished-at="2021-08-23T11:03:44 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[AccuWeather : 17.0 vs OpenWeather :16.22 did not match exactly! - did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: AccuWeather : 17.0 vs OpenWeather :16.22 did not match exactly! - did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at Tests.CompareTemperature.TC3_CompareTwoWeathers(CompareTemperature.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC3_CompareTwoWeathers -->
        <test-method status="FAIL" signature="TC4_VerifyDifferenceInRange()[pri:3, instance:Tests.CompareTemperature@71a794e5]" name="TC4_VerifyDifferenceInRange" duration-ms="0" started-at="2021-08-23T11:03:44 IST" finished-at="2021-08-23T11:03:44 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The difference: 0.7800000000000011 is out of range. The range is 0.5 did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The difference: 0.7800000000000011 is out of range. The range is 0.5 did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at Tests.CompareTemperature.TC4_VerifyDifferenceInRange(CompareTemperature.java:128)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC4_VerifyDifferenceInRange -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:Tests.CompareTemperature@71a794e5]" name="teardown" is-config="true" duration-ms="670" started-at="2021-08-23T11:03:44 IST" finished-at="2021-08-23T11:03:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Tests.CompareTemperature -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
